Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HouseBuying.Data;
using HouseBuying.Models;
using Microsoft.AspNetCore.Authorization;

namespace HouseBuying.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AddressesController : Controller
    {
        private readonly AppDBContext _context;

        public AddressesController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Addresses
        public async Task<IActionResult> Index()
        {
              return _context.Addresses != null ? 
                          View(await _context.Addresses.ToListAsync()) :
                          Problem("Entity set 'AppDBContext.Addresses'  is null.");
        }

        // GET: Addresses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Addresses == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // GET: Addresses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Street,Ward,District,Province")] Address address)
        {
            if (ModelState.IsValid)
            {
                _context.Add(address);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(address);
        }

        // GET: Addresses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Addresses == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses.FindAsync(id);
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }

        // POST: Addresses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Street,Ward,District,Province")] Address address)
        {
            if (id != address.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressExists(address.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(address);
        }

        // GET: Addresses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Addresses == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Addresses == null)
            {
                return Problem("Entity set 'AppDBContext.Addresses'  is null.");
            }
            var address = await _context.Addresses.FindAsync(id);
            if (address != null)
            {
                _context.Addresses.Remove(address);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AddressExists(int id)
        {
          return (_context.Addresses?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HouseBuying.Data;
using HouseBuying.Models;
using Microsoft.AspNetCore.Authorization;

namespace HouseBuying.Controllers
{
    [Authorize(Roles="Admin")]
    public class HouseController : Controller
    {
        private readonly AppDBContext _context;

        public HouseController(AppDBContext context)
        {
            _context = context;
        }

        // GET: House
        public async Task<IActionResult> Index()
        {
            var appDBContext = _context.Houses.Include(h => h.Address);
            return View(await appDBContext.ToListAsync());
        }

        // GET: House/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Houses == null)
            {
                return NotFound();
            }

            var house = await _context.Houses
                .Include(h => h.Address)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (house == null)
            {
                return NotFound();
            }

            return View(house);
        }


        public IActionResult GetDistricts(string province)
        {
            var districts = _context.Addresses
                .Where(a => a.Province == province)
                .Select(a => a.District)
                .Distinct()
                .ToList();

            return Json(districts);
        }

        public IActionResult GetWards(string province, string district)
        {
            var wards = _context.Addresses
                .Where(a => a.Province == province && a.District == district)
                .Select(a => a.Ward)
                .Distinct()
                .ToList();

            return Json(wards);
        }

        public IActionResult GetStreets(string province, string district, string ward)
        {
            var streets = _context.Addresses
                .Where(a => a.Province == province && a.District == district && a.Ward == ward)
                .Select(a => a.Street)
                .Distinct()
                .ToList();

            return Json(streets);
        }
        public IActionResult GetAddressId(string province, string district, string ward, string street)
        {
            var addressId = _context.Addresses
                .Where(a => a.Province == province && a.District == district && a.Ward == ward && a.Street == street)
                .Select(a => a.Id)
                .FirstOrDefault();

            return Json(addressId);
        }

        // GET: House/Create
        public IActionResult Create()
        {
            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "Id");

            // Lấy danh sách tỉnh
            ViewBag.Provinces = _context.Addresses.Select(a => a.Province).Distinct().ToList();


            return View();
        }

        // POST: House/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Bedrooms,Bathrooms,Price,ImageURL,Status,AddressId")] House house)
        {
           
            if (house!=null)
            {
                _context.Add(house);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }



            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "Id", house.AddressId);


            return View(house);
        }

        // GET: House/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Houses == null)
            {
                return NotFound();
            }

            var house = await _context.Houses.FindAsync(id);
            if (house == null)
            {
                return NotFound();
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "Id", house.AddressId);
            return View(house);
        }

        // POST: House/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Bedrooms,Bathrooms,Price,ImageURL,Status,AddressId")] House house)
        {
            try
            {
                if (id != house.Id)
                {
                    return NotFound();
                }

           
                
                    _context.Update(house);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                

                ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "Id", house.AddressId);
                return View(house);
            }
            catch (Exception ex)
            {
                // Log or display the exception
                Console.WriteLine(ex.Message);
                throw; // Rethrow the exception to see details in the browser
            }
            // Repopulate the ViewBag.Provinces in case of an error

            
        }

        // GET: House/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Houses == null)
            {
                return NotFound();
            }

            var house = await _context.Houses
                .Include(h => h.Address)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (house == null)
            {
                return NotFound();
            }

            return View(house);
        }

        // POST: House/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Houses == null)
            {
                return Problem("Entity set 'AppDBContext.Houses'  is null.");
            }
            var house = await _context.Houses.FindAsync(id);
            if (house != null)
            {
                _context.Houses.Remove(house);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HouseExists(int id)
        {
          return (_context.Houses?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/OrdersController.cs
using HouseBuying.Data;
using HouseBuying.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace HouseBuying.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        
        AppDBContext _context;
        private readonly ShoppingCart _shoppingCart;

        public OrdersController( ShoppingCart shoppingCart, AppDBContext context)
        {
     
            _shoppingCart = shoppingCart;
            _context = context;
         
        }
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _context.Orders.Include(n => n.OrderItems).ThenInclude(n => n.House).Include(n => n.User).ToListAsync();

            if (userRole != "Admin")
            {
                orders = orders.Where(n => n.UserId == userId).ToList();
            }


            return View(orders);
        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _context.Houses.FindAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));

        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _context.Houses.FindAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));

        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            var order = new Order()
            {
                UserId = userId,
                Email = userEmailAddress
            };
            await _context.Orders.AddAsync(order);
            await _context.SaveChangesAsync();

            foreach (var item in items)
            {
                var orderItem = new OrderItem()
                {
                    Amount = item.Amount,
                    HouseId = item.House.Id,
                    OrderId = order.Id,
                    Price = item.House.Price
                };
                await _context.OrderItems.AddAsync(orderItem);
                item.House.Status = "SOLD";
            }
            await _context.SaveChangesAsync();


            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> GetAllOrders()
        {
 

            var orders = await _context.Orders.Include(n => n.OrderItems).ThenInclude(n => n.House).Include(n => n.User).ToListAsync();


            return View(orders);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RemoveOrder(int id)
        {


            var order = await _context.Orders
                .Include(o => o.OrderItems)  // Include OrderItems for eager loading
                .ThenInclude(oi => oi.House)
                 .FirstOrDefaultAsync(o => o.Id == id);

            if (order == null)
            {
                return NotFound();
            }
            // Update House status to "Available" for each associated OrderItem
            foreach (var orderItem in order.OrderItems)
            {
                orderItem.House.Status = "AVAILABLE";
                // If you have a specific status enumeration, replace "Available" with the appropriate value
            }
            // Remove associated OrderItems
            _context.OrderItems.RemoveRange(order.OrderItems);

            // Remove the Order
            _context.Orders.Remove(order);
            
            await _context.SaveChangesAsync();


            return RedirectToAction("GetAllOrders");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HouseBuying</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HouseBuying.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container p-2">
                <!-- Branding -->
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HouseBuying</a>
                

                <!-- Mobile Toggle Button -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar Items -->
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <!-- Left-aligned Menu Items -->
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link item-header text-dark" asp-controller="Home" asp-action="Index"><i class="bi bi-house-door"></i> Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link item-header dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-controller="House" asp-action="Index"><i class="bi bi-headset"></i> House</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Addresses" asp-action="Index"><i class="bi bi-headset"></i> Address</a>
                                    </li
                                    <li>
                                        <a class="dropdown-item" asp-controller="Orders" asp-action="GetAllOrders"><i class="bi bi-headset"></i> Orders</a>
                                    </li>
                                  
                                   

                                </ul>
                            </li>
                        }
                    </ul>

                    <!-- Right-aligned Search Form -->
             
                    <form class="d-flex" role="search" asp-controller="Home" asp-action="Filter">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searchString">
                        <button class="btn btn-search " type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HouseBuying - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>